services:
  rails:
    build: .
    restart: always
    command: bash -c "rm /web/tmp/pids/server.pid; rails server -p 3000 -b 0.0.0.0"
    working_dir: /web
    expose:
      - 3000
    environment:
      RAILS_ENV: development
    volumes:
      - .:/web
      - bundle:/bundle
    ports:
      - 3000:3000
    env_file:
      - .env
volumes:
  bundle: