dependency_of:
  - rails
version:
  ask: true
  default: 4.0.8
services:
  redis:
    image: redis:$REDIS_VERSION
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379